-- ==============================================================
-- Friends Library Management System - Database Seed Script
-- Auto-generated from consolidated master data
-- ==============================================================

-- 1. Create Admins Table (if not exists) & default admin
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

INSERT INTO admins (username, password)
VALUES ('admin@friendslibrary.com', 'Tarun@2604')
ON CONFLICT (username) DO UPDATE SET password = EXCLUDED.password;

-- 2. Create Students Table
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo TEXT,
    "seatNo" TEXT,
    name TEXT NOT NULL,
    shift TEXT,
    mobile TEXT,
    aadhar TEXT,
    "joiningDate" TEXT,
    plan TEXT,
    "cardNo" TEXT,
    fee NUMERIC,
    mode TEXT,
    "lastPaid" TEXT,
    "dueDate" TEXT,
    remarks TEXT,
    password TEXT DEFAULT '123456'
);

-- Ensure password column exists on existing installations
ALTER TABLE students ADD COLUMN IF NOT EXISTS password TEXT DEFAULT '123456';

-- 3. Create Past Members Table
CREATE TABLE IF NOT EXISTS past_members (
    id BIGINT PRIMARY KEY,
    photo TEXT,
    "seatNo" TEXT,
    name TEXT NOT NULL,
    shift TEXT,
    mobile TEXT,
    aadhar TEXT,
    "joiningDate" TEXT,
    plan TEXT,
    "cardNo" TEXT,
    fee NUMERIC,
    mode TEXT,
    "lastPaid" TEXT,
    "dueDate" TEXT,
    remarks TEXT,
    password TEXT DEFAULT '123456',
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE past_members ADD COLUMN IF NOT EXISTS password TEXT DEFAULT '123456';

-- 4. Create Pending Registrations Table
CREATE TABLE IF NOT EXISTS pending_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo TEXT,
    "seatNo" TEXT,
    name TEXT NOT NULL,
    shift TEXT,
    mobile TEXT,
    aadhar TEXT,
    "joiningDate" TEXT,
    plan TEXT,
    "cardNo" TEXT,
    fee NUMERIC,
    mode TEXT,
    "lastPaid" TEXT,
    "dueDate" TEXT,
    remarks TEXT,
    password TEXT DEFAULT '123456',
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE pending_registrations ADD COLUMN IF NOT EXISTS password TEXT DEFAULT '123456';

-- 5. Create Receipts Table
CREATE TABLE IF NOT EXISTS receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    receipt_no TEXT,
    student_name TEXT,
    mobile TEXT,
    seat_no TEXT,
    shift TEXT,
    fee NUMERIC,
    mode TEXT,
    plan TEXT,
    payment_date TEXT,
    due_date TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE receipts ADD COLUMN IF NOT EXISTS mobile TEXT;
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS shift TEXT;
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS due_date TEXT;

-- 6. Insert All 97 Students
INSERT INTO students (id, "seatNo", name, shift, mobile, aadhar, "joiningDate", plan, "cardNo", fee, mode, "lastPaid", "dueDate", remarks)
VALUES
(1, 'G8', 'Himanshu Partap', '12 Hours', '9125462201', '', '2026-05-10', 'Monthly', '', 1350, 'Cash', '2026-07-10', '2026-08-09', 'terminate'),
(2, 'A9', 'Neeru Yadav', '12 Hours', '9289572374', '', '2026-08-02', 'Monthly', '', 1350, 'Cash', '2026-09-02', '2026-10-02', ''),
(3, 'C1', 'Anchal Gupta', '12 Hours', '8527933057', '', '2026-04-03', 'Monthly', '', 1350, 'Cash', '2026-09-03', '2026-10-03', ''),
(4, 'H10', 'Binit Mishra', '12 Hours', '7979823634', '', '2026-05-02', 'Monthly', '', 1200, 'Cash', '2026-10-02', '2026-11-01', ''),
(5, 'B6', 'Himanshu Sharma', '12 Hours', '9084113671', '', '2026-04-15', 'Monthly', '', 1350, 'Cash', '2026-07-15', '2026-08-14', 'DON’T know him'),
(6, 'E10', 'Subham Saini', '12 Hours', '8796210433', '', '', 'Monthly', '', 0, 'Cash', '', '', ''),
(7, 'E1', 'Sahil Kumar Singh', '12 Hours', '8081022788', '', '', 'Monthly', '', 0, 'Cash', '', '', ''),
(8, 'J', 'Nancy Yadav', '12 Hours', '8307001181', '', '2026-04-03', 'Monthly', '', 3600, 'Cash', '2026-08-03', '2026-09-02', '3 months fess (APRIL,MAY,JUNE)'),
(9, 'D3', 'Agyat Choudhary', '12 Hours', '8826783185', '', '', 'Monthly', '', 0, 'Cash', '', '', ''),
(10, 'G10', 'Manisha Yadav', '12 Hours', '9810755027', '', '2026-04-02', 'Monthly', '', 1200, 'Cash', '2026-09-02', '2026-10-02', 'Cash paid to tarun'),
(11, 'D6', 'Manish Yadav', '12 Hours', '9136991369', '', '2026-05-06', 'Monthly', 'S-1', 1350, 'Cash', '2026-08-06', '2026-09-05', ''),
(12, 'E6', 'Shivam Verma', '12 Hours', '8557836955', '', '', 'Monthly', '', 0, 'Cash', '', '', ''),
(13, 'H1', 'Deepika Yadav', '12 Hours', '8295307758', '', '2026-04-01', 'Monthly', '', 1350, 'Cash', '2026-07-01', '2026-07-31', 'Cash paid'),
(14, 'B9', 'Chhavi', '12 Hours', '8860388936', '', '', 'Monthly', '', 0, 'Cash', '', '', ''),
(15, 'Pending', 'Annu Yadav (Chacha Sombir)', '6 Hours', '8800047234', '', '', 'Monthly', '', 0, 'Cash', '', '', ''),
(16, 'C7', 'Hema Phogat', '12 Hours', '8800170950', '', '2026-04-12', 'Monthly', '', 1200, 'Cash', '2026-08-12', '2026-09-11', 'June fess pending'),
(17, 'B10', 'Satyam Ojha', '12 Hours', '9667697573', '', '2026-05-02', 'Monthly', '', 1350, 'Cash', '2026-08-02', '2026-09-01', ''),
(18, 'H7', 'Vidhi Yadav', '12 Hours', '9217811377', '', '2026-05-22', 'Monthly', '', 1500, 'Cash', '2026-08-22', '2026-09-21', 'terminate membeship'),
(19, 'Pending', 'Akansha', '12 Hours', '8287889923', '', '2026-07-02', 'Monthly', '', 0, 'Cash', '2026-08-02', '2026-09-01', ''),
(20, 'A7', 'Ghanshyam', '12 Hours', '9808902012', '', '2026-05-02', 'Monthly', '', 1350, 'Cash', '2026-09-02', '2026-10-02', ''),
(21, 'A6', 'Naveen Meel', '12 Hours', '8769471595', '', '2026-05-02', 'Monthly', '', 3000, 'Cash', '2026-05-02', '2026-07-31', '300 bal'),
(22, 'Pending', 'Vipin Kurmar', '12 Hours', '9053101898', '', '', 'Customize', 'S-2', 100, 'Cash', '', '', ''),
(23, 'Pending', 'Sushant', '12 Hours', '7290058300', '', '', 'Monthly', '', 0, 'Cash', '', '', 'he will talk goru'),
(24, 'Pending', 'Prince', '12 Hours', '8700788948', '', '', 'Monthly', '', 0, 'Cash', '', '', ''),
(25, 'H5', 'M.Kavinmani', '12 Hours', '70067840053', '', '', 'Monthly', '', 0, 'Cash', '', '', ''),
(26, 'J', 'Arun Gupta', '6 Hours', '9560629914', '', '2026-04-02', 'Monthly', '', 1000, 'Cash', '2026-10-02', '2026-11-01', 'Look register'),
(27, 'G6', 'Vivek Tiwari', '12 Hours', '9711961946', '', '2026-04-16', 'Monthly', '', 1350, 'Cash', '2026-07-16', '2026-08-15', 'remove his books'),
(28, 'Pending', 'Pruthvi Raj', '6 Hours', '9527020436', '', '2026-08-27', 'Monthly', '', 1200, 'Cash', '2026-08-27', '2026-09-26', 'will re join after 15 aug'),
(29, 'E6', 'Harsh Kumar', '6 Hours', '7903089965', '', '2026-09-04', 'Monthly', 'S3', 1000, 'Cash', '2026-10-04', '2026-11-03', 'check msg for fees'),
(30, 'Pending', 'Karan Aggarwal', '6 Hours', '9034220879', '', '2026-05-01', 'Monthly', '', 1000, 'Cash', '2026-07-01', '2026-07-31', 'Due on 01 july 2026'),
(31, 'Pending', 'Rishab Sharma', '6 Hours', '9871510313', '', '2026-05-19', 'Monthly', '', 800, 'Cash', '2026-09-19', '2026-10-19', 'Due on 19 JUNE 2026'),
(32, 'Pending', 'Parvesh B', '6 Hours', '9306935099', '', '2026-05-07', 'Monthly', '', 900, 'Cash', '2026-09-07', '2026-10-07', '900 recived'),
(33, 'E7', 'Naman Rawat', '24 Hours', '9634618514', '', '2026-05-02', 'Monthly', '', 1500, 'Cash', '2026-07-02', '2026-08-01', 'Due on 02 july 2026'),
(34, 'H4', 'Monika Choudhary', '12 Hours', '9650587191', '', '2026-04-08', 'Monthly', '', 1200, 'Cash', '2026-09-08', '2026-10-08', 'Due on 03 june2026'),
(35, 'B4', 'Ajay Yadav', '12 Hours', '7701822202', '', '2026-04-04', 'Monthly', '', 1500, 'Cash', '2026-09-04', '2026-10-04', 'cash paid 1500'),
(36, 'H3', 'Hariom Rai', '12 Hours', '8595018073', '', '2026-07-02', 'Monthly', '', 1350, 'Cash', '2026-07-02', '2026-08-01', 'Terminate'),
(37, 'B7', 'Radhey Sahu', '12 Hours', '9650165364', '', '2026-06-01', 'Monthly', '', 1400, 'Cash', '2026-09-01', '2026-10-01', 'DUE 01 JULY 2026'),
(38, 'F4', 'Laxmi Sehrawat', '12 Hours', '7015575687/9812700000', '', '2026-02-02', 'Monthly', '', 1300, 'Cash', '2026-07-02', '2026-08-01', 'Fess paid 2300 bal 300 more details check whatsapp'),
(39, 'Pending', 'Raksha Wankhede', '6 Hours', '6266138072', '', '2026-03-27', 'Customize', '', 1800, 'Cash', '2026-07-27', '2026-09-25', 'DUE on 27 Aug 2026'),
(40, 'C10', 'Kushal Shekwat', '12 Hours', '8796433231', '', '', 'Monthly', '', 0, 'Cash', '', '', ''),
(41, 'Pending', 'Nitesh Vishwkrma', '6 Hours', '7879200776', '', '2026-05-02', 'Monthly', '', 900, 'Cash', '2026-10-02', '2026-11-01', ''),
(42, 'Pending', 'Shalu Yadav', '12 Hours', '8383932596', '', '2026-06-03', 'Monthly', '', 1300, 'Cash', '2026-09-03', '2026-10-03', ''),
(43, 'Pending', 'Neeraj Yadav', '12 Hours', '8527519495', '', '', 'Monthly', '', 0, 'Cash', '', '', ''),
(44, 'Pending', 'Niharika', '12 Hours', '8168689751', '', '2026-08-02', 'Monthly', '', 1500, 'Cash', '2026-08-02', '2026-09-01', ''),
(45, 'Pending', 'Akshay Bhau', '12 Hours', '7030276291', '', '2026-08-22', 'Monthly', '', 1500, 'Cash', '2026-09-22', '2026-10-22', ''),
(46, 'Pending', 'Shri ram hardware', '6 Hours', '', '', '2026-05-02', 'Monthly', 'Yes', 800, 'Cash', '2026-05-02', '2026-06-01', 'Due on 02 May 2026'),
(47, 'E8', 'Pulkit Verma', '24 Hours', '', '', '2026-07-02', 'Monthly', '', 1500, 'Cash', '2026-08-02', '2026-09-01', 'Naman paid his july fess'),
(48, 'F7', 'Sachin Sharma', '12 Hours', '8008866501', '', '2026-04-03', 'Monthly', '', 1350, 'Cash', '2026-08-03', '2026-09-02', 'Due on 03 june 2026'),
(49, 'G4', 'Narender Kumar', '12 Hours', '9354763084', '', '2026-04-07', 'Quarterly', '', 2900, 'Cash', '2026-07-07', '2026-10-05', 'PAID FOR (7,8,9) MONTH'),
(50, 'A10', 'Sapna', '12 Hours', '8826243445', '', '2026-06-02', 'Monthly', '', 1350, 'Cash', '2026-09-02', '2026-10-02', 'Cash paid 1350'),
(51, 'Pending', 'Meenakshi', '12 Hours', '7303939552', '', '2026-07-02', 'Monthly', '', 1100, 'Cash', '2026-09-02', '2026-10-02', 'All Previous due clear'),
(52, 'Pending', 'Chenderkant', '12 Hours', '8307960509', '', '2026-06-11', 'Monthly', '', 1500, 'Cash', '2026-07-11', '2026-08-10', 'new admission'),
(53, 'Pending', 'Vipin Yadav', '12 Hours', '9891728504', '', '2026-06-14', 'Monthly', '', 1500, 'Cash', '2026-06-14', '2026-07-14', 'terminate'),
(54, 'Pending', 'Jitesh Parihar', '12 Hours', '7906777027', '', '2026-06-16', 'Monthly', '', 1500, 'Cash', '2026-09-16', '2026-10-16', 'new admission'),
(55, 'E4', 'Priya Yadav', '12 Hours', '9821599249', '', '2026-07-02', 'Monthly', '', 1500, 'Cash', '2026-08-02', '2026-09-01', 'new admission'),
(56, 'Pending', 'Vidhushi Yadav', '6 Hours', '8059163447', '', '2026-07-02', 'Monthly', '', 1200, 'Cash', '2026-09-02', '2026-10-02', 'new admission'),
(57, 'Pending', 'Khushi Yadav (Mannu Metha)', '12 Hours', '8930995435', '', '2026-07-02', 'Monthly', '', 1200, 'Cash', '2026-09-02', '2026-10-02', 'paid 3 months together (7,8,9)'),
(58, 'Pending', 'Shreyash', '12 Hours', '8545943312', '', '2026-07-04', 'Monthly', '', 1350, 'Cash', '2026-09-04', '2026-10-04', ''),
(59, 'Pending', 'Deepak Kumar', '12 Hours', '7011490356', '', '2026-07-03', 'Monthly', '', 1500, 'Cash', '2026-10-03', '2026-11-02', ''),
(60, 'Pending', 'Lokesh sharma', '12 Hours', '7206019105', '', '2026-07-02', 'Monthly', '', 1500, 'Cash', '2026-07-02', '2026-08-01', 'Terminate'),
(61, 'Pending', 'Rishita Joshi', '6 Hours', '7895845679', '', '2026-07-02', 'Monthly', '', 1200, 'Cash', '2026-07-02', '2026-08-01', 'terminate membeship'),
(62, 'E7', 'Navneet', '6 Hours', '7988249378', '', '2026-07-04', 'Monthly', '', 1200, 'Cash', '2026-08-04', '2026-09-03', 'paid 800 for this aug month only'),
(63, 'F10', 'Chunmesh Gurawaliya', '12 Hours', '9050360958', '', '2026-07-02', 'Monthly', '', 1500, 'Cash', '2026-10-02', '2026-11-01', ''),
(64, 'NR', 'Charan kumar  (NON RES)', '6 Hours', '9121491196', '', '2026-07-12', 'Monthly', '', 1200, 'Cash', '2026-07-12', '2026-08-11', 'NEW ADD'),
(65, 'G9', 'Piyush Raj', '12 Hours', '9217497149', '', '2026-07-12', 'Monthly', '', 1500, 'Cash', '2026-08-12', '2026-09-11', 'NEW ADD'),
(66, 'Pending', 'Muskan Rajput', '12 Hours', '8799766581', '', '2026-07-02', 'Monthly', '', 1350, 'Cash', '2026-07-02', '2026-08-01', 'Terminate'),
(67, 'Pending', 'Rahul', '12 Hours', '7495048289', '', '2026-07-08', 'Monthly', '', 1500, 'Cash', '2026-07-08', '2026-08-07', 'Terminate'),
(68, 'Pending', 'leesha', '12 Hours', '8595583809', '', '2026-07-14', 'Monthly', '', 1500, 'Cash', '2026-09-14', '2026-10-14', 'NEW ADD'),
(69, 'Pending', 'Vishal Nehra', '12 Hours', '9350365152', '', '2026-07-06', 'Monthly', '', 1500, 'Cash', '2026-07-06', '2026-08-05', 'NEW ADD'),
(70, 'Pending', 'Sonu Rawat', '12 Hours', '7056275097', '', '2026-06-22', 'Monthly', '', 1500, 'Cash', '2026-07-22', '2026-08-21', 'NEW ADD'),
(71, 'Pending', 'Vinay Yadav', '12 Hours', '9717862004', '', '2026-07-20', 'Monthly', '', 1200, 'Cash', '2026-07-20', '2026-08-19', 'NEW ADD'),
(72, 'Pending', 'Ritika Yadav', '12 Hours', '7428645936', '', '2026-07-16', 'Monthly', '', 1350, 'Cash', '2026-07-16', '2026-08-15', 'NEW ADD'),
(73, 'Pending', 'Lakshita Verma', '6 Hours', '9541881102', '', '2026-09-01', 'Monthly', '', 1200, 'Cash', '2026-09-01', '2026-10-01', ''),
(74, 'Pending', 'Naveen kumar', '6 Hours', '9550344450', '', '2026-07-13', 'Monthly', '', 1000, 'Cash', '2026-09-13', '2026-10-13', 'NEW ADD'),
(75, 'Pending', 'Arun Kumar Pothala', '6 Hours', '6305046425', '', '2026-07-13', 'Monthly', '', 1000, 'Cash', '2026-08-13', '2026-09-12', 'New Add'),
(76, 'Pending', 'Kimti Kumari', '12 Hours', '9263171200', '', '2026-07-24', 'Monthly', '', 1350, 'Cash', '2026-07-24', '2026-08-23', 'New Add'),
(77, 'Pending', 'Faijan', '12 Hours', '7417628086', '', '2026-07-25', 'Monthly', '', 1350, 'Cash', '2026-07-25', '2026-08-24', 'Leave'),
(78, 'Pending', 'Gaurav Yadav', '12 Hours', '7840001141', '', '2026-10-02', 'Monthly', '', 1000, 'Cash', '2026-10-02', '2026-11-01', 'New Add'),
(79, 'Pending', 'Mohit Tanwar', '12 Hours', '9910686924', '', '2026-07-22', 'Monthly', '', 1200, 'Cash', '2026-07-22', '2026-08-21', ''),
(80, 'Pending', 'Gaju', '12 Hours', '9911559516', '', '2026-07-17', 'Monthly', '', 1350, 'Cash', '2026-09-17', '2026-10-17', ''),
(81, 'Pending', 'Kaushlender singh', '12 Hours', '9559328254', '', '2026-08-01', 'Monthly', '', 1500, 'Cash', '2026-08-01', '2026-08-31', ''),
(82, 'Pending', 'Brijesh Yadav', '12 Hours', '7428565462', '', '2026-08-18', 'Monthly', '', 1400, 'Cash', '2026-09-18', '2026-10-18', ''),
(83, 'Pending', 'Daksh Yadav', '12 Hours', '9953172575', '', '2026-08-18', 'Monthly', '', 1500, 'Cash', '2026-08-18', '2026-09-17', ''),
(84, 'Pending', 'Amit Kumar', '6 Hours', '8003670250', '', '2026-08-15', 'Monthly', '', 1000, 'Cash', '2026-08-15', '2026-09-14', ''),
(85, 'F2', 'Bainaboina', '6 Hours', '6302933859', '', '2026-08-16', 'Monthly', '', 1100, 'Cash', '2026-09-16', '2026-10-16', ''),
(86, 'Pending', 'Kundan kumar', '6 Hours', '8638896754', '', '2026-08-18', 'Monthly', '', 600, 'Cash', '2026-08-18', '', ''),
(87, 'Pending', 'Rahul kumar', '12 Hours', '7667689779', '', '2026-08-09', 'Monthly', '', 1500, 'Cash', '2026-08-09', '2026-09-08', ''),
(88, 'C8', 'Rahul Raj', '12 Hours', '8825351846', '', '2026-09-03', 'Monthly', '', 1350, 'Cash', '2026-09-03', '2026-10-03', ''),
(89, 'E5', 'Suchitra', '6 Hours', '9016587778', '', '2026-09-09', 'Monthly', '', 1200, 'Cash', '2026-09-09', '2026-10-09', ''),
(90, 'E8', 'Shashikant singh', '6 Hours', '9113192669', '', '2026-09-08', 'Monthly', '', 1400, 'Cash', '2026-09-08', '2026-10-08', ''),
(91, 'Pending', 'Saurabh Tiwari', '12 Hours', '7042712184', '', '2026-09-12', 'Monthly', '', 1500, 'Cash', '2026-09-12', '2026-10-12', ''),
(92, 'E3', 'Ashutosh Pandey', '12 Hours', '9873655721', '', '2026-09-20', 'Monthly', '', 1500, 'Cash', '2026-09-20', '2026-10-20', ''),
(93, 'NR', 'Harsh Yadav', '12 Hours', '9034450723', '', '2026-10-01', 'Monthly', '', 1500, 'Cash', '2026-10-01', '2026-10-31', 'only for 1 month'),
(94, 'NR', 'Rashid Khan', '6 Hours', '8003037715', '', '2026-09-09', 'Monthly', '', 1000, 'Cash', '2026-09-09', '2026-10-09', ''),
(95, 'Pending', 'Shivam Singh', '6 Hours', '9266104871', '', '2026-09-02', 'Monthly', '', 1200, 'Cash', '2026-09-02', '2026-10-02', ''),
(96, 'Pending', 'Piyush Mangal Chahande', '6 Hours', '8888203750', '', '2026-08-23', 'Monthly', '', 1200, 'Cash', '2026-09-23', '2026-10-23', ''),
(97, 'Pending', 'Krishna kumari', '6 Hours', '8103350714', '', '2026-09-17', 'Monthly', '', 900, 'Cash', '2026-09-17', '2026-10-17', '')
ON CONFLICT (id) DO UPDATE SET
  "seatNo" = EXCLUDED."seatNo",
  name = EXCLUDED.name,
  shift = EXCLUDED.shift,
  mobile = EXCLUDED.mobile,
  "joiningDate" = EXCLUDED."joiningDate",
  plan = EXCLUDED.plan,
  fee = EXCLUDED.fee,
  mode = EXCLUDED.mode,
  "lastPaid" = EXCLUDED."lastPaid",
  "dueDate" = EXCLUDED."dueDate",
  remarks = EXCLUDED.remarks;

SELECT setval(pg_get_serial_sequence('students', 'id'), coalesce(max(id), 1)) FROM students;
