-- ==============================================================
-- Friends Library - Sheet 3 (12Hr) & Sheet 6 (6Hr) Seed Script
-- Total Active Members: 46
-- ==============================================================

-- 1. Create Admins Table & Default Admin
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

INSERT INTO admins (username, password)
VALUES ('admin', 'password123')
ON CONFLICT (username) DO UPDATE SET password = EXCLUDED.password;

-- 2. Create Students Table
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo TEXT,
    "seatNo" TEXT,
    name TEXT NOT NULL,
    shift TEXT,
    mobile TEXT,
    aadhar TEXT,
    "joiningDate" TEXT,
    plan TEXT,
    "cardNo" TEXT,
    fee NUMERIC,
    mode TEXT,
    "lastPaid" TEXT,
    "dueDate" TEXT,
    remarks TEXT
);

-- 3. Insert 46 Active Students from Sheet 3 and Sheet 6
INSERT INTO students (id, "seatNo", name, shift, mobile, aadhar, "joiningDate", plan, "cardNo", fee, mode, "lastPaid", "dueDate", remarks)
VALUES
(1, 'A9', 'Neeru Yadav', '12 Hours', '9289572374', '', '2026-08-02', 'Monthly', '', 1350, 'Cash', '2026-09-02', '2026-10-02', ''),
(2, 'C1', 'Anchal Gupta', '12 Hours', '8527933057', '', '2026-04-03', 'Monthly', '', 1350, 'Cash', '2026-09-03', '2026-10-03', ''),
(3, 'H10', 'Binit Mishra', '12 Hours', '7979823634', '', '2026-05-02', 'Monthly', '', 1200, 'Cash', '2026-10-02', '2026-11-01', ''),
(4, 'G10', 'Manisha Yadav', '12 Hours', '9810755027', '', '2026-04-02', 'Monthly', '', 1200, 'Cash', '2026-09-02', '2026-10-02', ''),
(5, 'A7', 'Ghanshyam', '12 Hours', '9808902012', '', '2026-05-02', 'Monthly', '', 1350, 'Cash', '2026-09-02', '2026-10-02', ''),
(6, 'H4', 'Monika Choudhary', '12 Hours', '9650587191', '', '2026-04-08', 'Monthly', '', 1200, 'Cash', '2026-09-08', '2026-10-08', ''),
(7, 'B4', 'Ajay Yadav', '12 Hours', '7701822202', '', '2026-04-04', 'Monthly', '', 1500, 'Cash', '2026-09-04', '2026-10-04', ''),
(8, 'B7', 'Radhey Sahu', '12 Hours', '9650165364', '', '2026-06-01', 'Monthly', '', 1400, 'Cash', '2026-09-01', '2026-10-01', ''),
(9, 'Pending', 'Shalu Yadav', '12 Hours', '8383932596', '', '2026-06-03', 'Monthly', '', 1300, 'Cash', '2026-09-03', '2026-10-03', ''),
(10, 'G4', 'Narender Kumar', '12 Hours', '9354763084', '', '2026-04-07', 'Quarterly', '', 2900, 'Cash', '2026-07-07', '2026-10-05', 'PAID FOR (7,8,9) MONTH'),
(11, 'A10', 'Sapna', '12 Hours', '8826243445', '', '2026-06-02', 'Monthly', '', 1350, 'Cash', '2026-09-02', '2026-10-02', ''),
(12, 'Pending', 'Meenakshi', '12 Hours', '7303939552', '', '2026-07-02', 'Monthly', '', 1100, 'Cash', '2026-09-02', '2026-10-02', ''),
(13, 'Pending', 'Jitesh Parihar', '12 Hours', '7906777027', '', '2026-06-16', 'Monthly', '', 1500, 'Cash', '2026-09-16', '2026-10-16', ''),
(14, 'Pending', 'Khushi Yadav (Mannu Metha)', '12 Hours', '8930995435', '', '2026-07-02', 'Monthly', '', 1200, 'Cash', '2026-09-02', '2026-10-02', 'paid 3 months together (7,8,9)'),
(15, 'Pending', 'Shreyash', '12 Hours', '8545943312', '', '2026-07-04', 'Monthly', '', 1350, 'Cash', '2026-09-04', '2026-10-04', ''),
(16, 'Pending', 'Deepak Kumar', '12 Hours', '7011490356', '', '2026-07-03', 'Monthly', '', 1500, 'Cash', '2026-10-03', '2026-11-02', ''),
(17, 'F10', 'Chunmesh Gurawaliya', '12 Hours', '9050360958', '', '2026-07-02', 'Monthly', '', 1500, 'Cash', '2026-10-02', '2026-11-01', ''),
(18, 'G9', 'Piyush Raj', '12 Hours', '9217497149', '', '2026-07-12', 'Monthly', '', 1500, 'Cash', '2026-08-12', '2026-09-11', ''),
(19, 'Pending', 'leesha', '12 Hours', '8595583809', '', '2026-07-14', 'Monthly', '', 1500, 'Cash', '2026-09-14', '2026-10-14', ''),
(20, 'Pending', 'Faijan', '12 Hours', '7417628086', '', '2026-07-25', 'Monthly', '', 1350, 'Cash', '2026-07-25', '2026-08-24', 'Leave'),
(21, 'Pending', 'Gaurav Yadav', '12 Hours', '7840001141', '', '2026-10-02', 'Monthly', '', 1000, 'Cash', '2026-10-02', '2026-11-01', ''),
(22, 'Pending', 'Gaju', '12 Hours', '9911559516', '', '2026-07-17', 'Monthly', '', 1350, 'Cash', '2026-09-17', '2026-10-17', ''),
(23, 'Pending', 'Kaushlender singh', '12 Hours', '9559328254', '', '2026-08-01', 'Monthly', '', 1500, 'Cash', '2026-08-01', '2026-08-31', ''),
(24, 'Pending', 'Brijesh Yadav', '12 Hours', '7428565462', '', '2026-08-18', 'Monthly', '', 1400, 'Cash', '2026-09-18', '2026-10-18', ''),
(25, 'Pending', 'Akshay Bhau', '12 Hours', '7030276291', '', '2026-08-22', 'Monthly', '', 1500, 'Cash', '2026-09-22', '2026-10-22', ''),
(26, 'Pending', 'Saurabh Tiwari', '12 Hours', '7042712184', '', '2026-09-12', 'Monthly', '', 1500, 'Cash', '2026-09-12', '2026-10-12', ''),
(27, 'E8', 'Shashikant Singh', '12 Hours', '9113192669', '', '2026-09-09', 'Monthly', '', 1400, 'Cash', '2026-09-09', '2026-10-09', ''),
(28, 'C8', 'Rahul Raj', '12 Hours', '8825351846', '', '2026-09-03', 'Monthly', '', 1350, 'Cash', '2026-09-03', '2026-10-03', ''),
(29, 'E3', 'Ashutosh Pandey', '12 Hours', '9873655721', '', '2026-09-20', 'Monthly', '', 1500, 'Cash', '2026-09-20', '2026-10-20', ''),
(30, 'NR', 'Harsh Yadav', '12 Hours', '9034450723', '', '2026-10-01', 'Monthly', '', 1500, 'Cash', '2026-10-01', '2026-10-31', 'only for 1 month'),
(31, 'J', 'Arun Gupta', '6 Hours', '9560629914', '', '2026-04-02', 'Monthly', '', 1000, 'Cash', '2026-10-02', '2026-11-01', ''),
(32, 'Pending', 'Rishab Sharma', '6 Hours', '9871510313', '', '2026-05-19', 'Monthly', '', 800, 'Cash', '2026-09-19', '2026-10-19', ''),
(33, 'Pending', 'Parvesh B', '6 Hours', '9306935099', '', '2026-05-07', 'Monthly', '', 900, 'Cash', '2026-09-07', '2026-10-07', ''),
(34, 'Pending', 'Raksha Wankhede', '6 Hours', '6266138072', '', '2026-03-27', 'Customize', '', 1800, 'Cash', '2026-07-27', '2026-09-25', ''),
(35, 'Pending', 'Nitesh Vishwkrma', '6 Hours', '7879200776', '', '2026-05-02', 'Monthly', '', 900, 'Cash', '2026-10-02', '2026-11-01', ''),
(36, 'Pending', 'Shri ram hardware', '6 Hours', '', '', '2026-05-02', 'Monthly', 'Yes', 800, 'Cash', '2026-05-02', '2026-06-01', ''),
(37, 'Pending', 'Vidhushi Yadav', '6 Hours', '8059163447', '', '2026-07-02', 'Monthly', '', 1200, 'Cash', '2026-09-02', '2026-10-02', ''),
(38, 'Pending', 'Naveen kumar', '6 Hours', '9550344450', '', '2026-07-13', 'Monthly', '', 1000, 'Cash', '2026-09-13', '2026-10-13', ''),
(39, 'F2', 'Bainaboina', '6 Hours', '6302933859', '', '2026-08-16', 'Monthly', '', 1100, 'Cash', '2026-09-16', '2026-10-16', ''),
(40, 'E5', 'Suchitra', '6 Hours', '9016587778', '', '2026-09-09', 'Monthly', '', 1200, 'Cash', '2026-09-09', '2026-10-09', ''),
(41, 'E8', 'Shashikant singh', '6 Hours', '9113192669', '', '2026-09-08', 'Monthly', '', 1400, 'Cash', '2026-09-08', '2026-10-08', ''),
(42, 'E6', 'Harsh Kumar', '6 Hours', '7903089965', '', '2026-09-04', 'Monthly', '', 1000, 'Cash', '2026-10-04', '2026-11-03', 'check msg for fees'),
(43, 'NR', 'Rashid Khan', '6 Hours', '8003037715', '', '2026-09-09', 'Monthly', '', 1000, 'Cash', '2026-09-09', '2026-10-09', ''),
(44, 'Pending', 'Shivam Singh', '6 Hours', '9266104871', '', '2026-09-02', 'Monthly', '', 1200, 'Cash', '2026-09-02', '2026-10-02', ''),
(45, 'Pending', 'Piyush Mangal Chahande', '6 Hours', '8888203750', '', '2026-08-23', 'Monthly', '', 1200, 'Cash', '2026-09-23', '2026-10-23', ''),
(46, 'Pending', 'Krishna kumari', '6 Hours', '8103350714', '', '2026-09-17', 'Monthly', '', 900, 'Cash', '2026-09-17', '2026-10-17', '')
ON CONFLICT (id) DO UPDATE SET
  "seatNo" = EXCLUDED."seatNo",
  name = EXCLUDED.name,
  shift = EXCLUDED.shift,
  mobile = EXCLUDED.mobile,
  "joiningDate" = EXCLUDED."joiningDate",
  plan = EXCLUDED.plan,
  fee = EXCLUDED.fee,
  mode = EXCLUDED.mode,
  "lastPaid" = EXCLUDED."lastPaid",
  "dueDate" = EXCLUDED."dueDate",
  remarks = EXCLUDED.remarks;

SELECT setval(pg_get_serial_sequence('students', 'id'), coalesce(max(id), 1)) FROM students;
